# Introduction

In this set of exercises we will work with a Wine Reviews dataset. The dataset contains reviews with columns for country, description, designation, points, price, province, region, taster info, title, variety, and winery.

Run the following cell to load your data.

In [1]:
import pandas as pd
import numpy as np

np.random.seed(42)
n = 150

country_pool = ['Italy', 'Portugal', 'US', 'Spain', 'Germany',
                'France', 'Australia', 'New Zealand', 'Argentina', 'Chile']
countries = list(np.random.choice(country_pool, n))
countries[0] = 'Italy'
countries[1] = 'Portugal'
countries[2] = 'US'
countries[3] = 'US'
countries[5] = 'Spain'
countries[8] = 'Germany'
countries[10] = 'US'
countries[100] = 'US'
for i in [50, 51]:
    countries[i] = 'Australia'
countries[52] = 'New Zealand'
for i in [20, 35, 70, 90, 130]:
    countries[i] = 'Italy'

variety_pool = ['White Blend', 'Portuguese Red', 'Pinot Gris', 'Riesling',
                'Sangiovese', 'Pinot Noir', 'Cabernet Sauvignon', 'Chardonnay',
                'Tempranillo-Merlot', 'Shiraz']
varieties = list(np.random.choice(variety_pool, n))

points = list(np.random.randint(82, 95, n))
points[50] = 96
points[51] = 98
points[52] = 95

province_map = {
    'Italy': 'Sicily & Sardinia', 'Portugal': 'Douro', 'US': 'California',
    'Spain': 'Northern Spain', 'Germany': 'Rheinhessen', 'France': 'Bordeaux',
    'Australia': 'Victoria', 'New Zealand': "Hawke's Bay",
    'Argentina': 'Mendoza', 'Chile': 'Maipo Valley',
}

reviews = pd.DataFrame({
    'country': countries,
    'description': [f'Wine description for review {i}.' for i in range(n)],
    'designation': [None if i % 5 == 0 else f'Label {i % 15}' for i in range(n)],
    'points': points,
    'price': [round(float(p), 1) for p in np.random.uniform(10, 300, n)],
    'province': [province_map[c] for c in countries],
    'region_1': [None if i % 3 == 0 else f'Region {i % 8}' for i in range(n)],
    'region_2': [None if i % 4 == 0 else f'Sub-region {i % 5}' for i in range(n)],
    'taster_name': [None if i % 5 == 0 else f'Taster {i % 6}' for i in range(n)],
    'taster_twitter_handle': [None if i % 5 == 0 else f'@taster{i % 6}' for i in range(n)],
    'title': [f'Winery {i % 20} {2010 + i % 10} Vintage Wine' for i in range(n)],
    'variety': varieties,
    'winery': [f'Winery {i % 20}' for i in range(n)],
})

pd.set_option('display.max_rows', 5)
print(f'Loaded {len(reviews)} wine reviews with {reviews.shape[1]} columns.')
print('Setup complete.')

Loaded 150 wine reviews with 13 columns.
Setup complete.

Look at an overview of your data by running the following line.

In [2]:
reviews.head()

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,Wine description for review 0.,NaN,86,60.2,Sicily & Sardinia,NaN,NaN,NaN,NaN,Winery 0 2010 Vintage Wine,Pinot Gris,Winery 0
1,Portugal,Wine description for review 1.,Label 1,89,135.8,Douro,Region 1,Sub-region 1,Taster 1,@taster1,Winery 1 2011 Vintage Wine,Cabernet Sauvignon,Winery 1
2,US,Wine description for review 2.,Label 2,94,125.6,California,Region 2,Sub-region 2,Taster 2,@taster2,Winery 2 2012 Vintage Wine,Pinot Noir,Winery 2
3,US,Wine description for review 3.,Label 3,82,188.6,California,NaN,Sub-region 3,Taster 3,@taster3,Winery 3 2013 Vintage Wine,Chardonnay,Winery 3
4,Australia,Wine description for review 4.,Label 4,86,194.2,Victoria,Region 4,NaN,Taster 4,@taster4,Winery 4 2014 Vintage Wine,Tempranillo-Merlot,Winery 4

# Exercises

## 1.

Select the `description` column from `reviews` and assign the result to the variable `desc`.

In [3]:
# Your code here
desc = reviews['description']
print(type(desc))
desc

<class 'pandas.Series'>

0        Wine description for review 0.
1        Wine description for review 1.
                     ...
148    Wine description for review 148.
149    Wine description for review 149.
Name: description, Length: 150, dtype: str

**Key insight:** `df['col']` and `df.col` both select a column and return a **Series** (not a DataFrame). Use bracket notation when the column name has spaces or conflicts with a DataFrame method name.

## 2.

Select the first value from the description column of `reviews`, assigning it to variable `first_description`.

In [4]:
first_description = desc.iloc[0]
first_description

'Wine description for review 0.'

**Alternative solutions:** `reviews.description.iloc[0]`, `reviews.description.loc[0]`, or `reviews.description[0]` all return the same value here.

**Key insight:** `.iloc[0]` is the preferred way — it selects by **integer position** (0-based), so it always gets the first element regardless of what the index labels are.

## 3.

Select the first row of data (the first record) from `reviews`, assigning it to the variable `first_row`.

In [5]:
first_row = reviews.iloc[0]
first_row

country                                 Italy
description    Wine description for review 0.
                            ...
variety                            Pinot Gris
winery                               Winery 0
Name: 0, Length: 13, dtype: object

**Key insight:** `.iloc[0]` on a **DataFrame** returns a **Series** representing that row — the column names become the index of the returned Series. Compare: `.iloc[0]` on a Series returns a scalar value.

## 4.

Select the first 10 values from the `description` column in `reviews`, assigning the result to variable `first_descriptions`.

Hint: format your output as a pandas Series.

In [6]:
first_descriptions = desc.iloc[0:10]
first_descriptions

0    Wine description for review 0.
1    Wine description for review 1.
                  ...
8    Wine description for review 8.
9    Wine description for review 9.
Name: description, Length: 10, dtype: str

**Alternative solutions:**
```python
first_descriptions = reviews.description.iloc[:10]   # start defaults to 0
first_descriptions = desc.head(10)                   # .head(n) is equivalent
first_descriptions = reviews.loc[:9, 'description']  # loc stop is inclusive, :9 = 10 rows
```

**Key insight:** `iloc` slicing follows Python stdlib convention — start included, stop **excluded**. So `iloc[0:10]` gives indices 0–9 (10 items).

## 5.

Select the records with index labels `1`, `2`, `3`, `5`, and `8`, assigning the result to the variable `sample_reviews`.

The result should be a DataFrame with 5 rows (all 13 columns) at those specific index labels.

In [7]:
sample_reviews = reviews.loc[[1, 2, 3, 5, 8]]
sample_reviews

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
1,Portugal,Wine description for review 1.,Label 1,89,135.8,Douro,Region 1,Sub-region 1,Taster 1,@taster1,Winery 1 2011 Vintage Wine,Cabernet Sauvignon,Winery 1
2,US,Wine description for review 2.,Label 2,94,125.6,California,Region 2,Sub-region 2,Taster 2,@taster2,Winery 2 2012 Vintage Wine,Pinot Noir,Winery 2
3,US,Wine description for review 3.,Label 3,82,188.6,California,NaN,Sub-region 3,Taster 3,@taster3,Winery 3 2013 Vintage Wine,Chardonnay,Winery 3
5,Spain,Wine description for review 5.,NaN,84,23.1,Northern Spain,Region 5,Sub-region 0,NaN,NaN,Winery 5 2015 Vintage Wine,Sangiovese,Winery 5
8,Germany,Wine description for review 8.,Label 8,85,155.9,Rheinhessen,Region 0,NaN,Taster 2,@taster2,Winery 8 2018 Vintage Wine,Shiraz,Winery 8

**Key insight:** Pass a **list** of labels to `.loc[]` to select non-contiguous rows. `loc[[1,2,3,5,8]]` returns rows with those exact index labels — not positions. Here labels and positions happen to match because the default index is 0, 1, 2, ...

## 6.

Create a variable `df` containing the `country`, `province`, `region_1`, and `region_2` columns of the records with the index labels `0`, `1`, `10`, and `100`.

The result should be a 4-row, 4-column DataFrame:

| | country | province | region_1 | region_2 |
|---|---|---|---|---|
| 0 | Italy | Sicily & Sardinia | ... | NaN |
| 1 | Portugal | Douro | NaN | NaN |
| 10 | US | California | ... | ... |
| 100 | US | California | ... | ... |

In [8]:
df = reviews.loc[[0, 1, 10, 100], ['country', 'province', 'region_1', 'region_2']]
df

      country           province  region_1      region_2
0       Italy  Sicily & Sardinia       NaN           NaN
1    Portugal              Douro  Region 1  Sub-region 1
10         US         California  Region 2  Sub-region 0
100        US         California  Region 4           NaN

**Key insight:** `.loc[row_selector, col_selector]` selects both rows and columns simultaneously by **label**. Pass lists to select multiple rows and multiple columns at once. The result keeps the original row index labels.

## 7.

Create a variable `df` containing the `country` and `variety` columns of the first 100 records.

Hint: you may use `loc` or `iloc`. Keep this `loc` vs `iloc` difference in mind:

> `iloc` uses the Python stdlib indexing scheme, where the first element of the range is included and the last one excluded.
> `loc`, meanwhile, indexes inclusively.

> This is particularly confusing when the DataFrame index is a simple numerical list, e.g. `0,...,1000`. In this case `df.iloc[0:1000]` will return 1000 entries, while `df.loc[0:1000]` returns 1001 of them! To get 1000 elements using `loc`, you will need to go one lower and ask for `df.loc[0:999]`.

In [9]:
df = reviews.loc[0:99, ['country', 'variety']]
df

        country             variety
0         Italy          Pinot Gris
1      Portugal  Cabernet Sauvignon
..          ...                 ...
98    Argentina            Riesling
99  New Zealand         White Blend

[100 rows x 2 columns]

**Alternative solutions:**
```python
cols = ['country', 'variety']
df = reviews.loc[:99, cols]       # :99 same as 0:99 with loc (inclusive stop)

cols_idx = [0, 11]                # country = col 0, variety = col 11
df = reviews.iloc[:100, cols_idx] # iloc stop exclusive: :100 gives rows 0-99
```

**Key insight:** `loc[0:99]` and `iloc[:100]` both return 100 rows, but via different conventions. Mixing them up is the most common pandas indexing mistake.

## 8.

Create a DataFrame `italian_wines` containing reviews of wines made in `Italy`. Hint: `reviews.country` equals what?

In [10]:
italian_wines = reviews[reviews.country == 'Italy']
italian_wines

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,Wine description for review 0.,NaN,86,60.2,Sicily & Sardinia,NaN,NaN,NaN,NaN,Winery 0 2010 Vintage Wine,Pinot Gris,Winery 0
20,Italy,Wine description for review 20.,NaN,89,142.9,Sicily & Sardinia,Region 4,NaN,NaN,NaN,Winery 0 2010 Vintage Wine,Pinot Gris,Winery 0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
144,Italy,Wine description for review 144.,Label 9,93,23.2,Sicily & Sardinia,NaN,NaN,Taster 0,@taster0,Winery 4 2014 Vintage Wine,White Blend,Winery 4
145,Italy,Wine description for review 145.,NaN,91,91.5,Sicily & Sardinia,Region 1,Sub-region 0,NaN,NaN,Winery 5 2015 Vintage Wine,White Blend,Winery 5

**Key insight:** `reviews.country == 'Italy'` produces a **boolean Series** (True/False for each row). Passing it inside `[]` filters the DataFrame, keeping only rows where the mask is True. This is called **boolean indexing** (or masking).

## 9.

Create a DataFrame `top_oceania_wines` containing all reviews with at least 95 points (out of 100) for wines from Australia or New Zealand.

In [11]:
top_oceania_wines = reviews.loc[
    (reviews.country.isin(['Australia', 'New Zealand']))
    & (reviews.points >= 95)
]
top_oceania_wines

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
50,Australia,Wine description for review 50.,NaN,96,117.9,Victoria,Region 2,Sub-region 0,NaN,NaN,Winery 10 2010 Vintage Wine,Pinot Noir,Winery 10
51,Australia,Wine description for review 51.,Label 6,98,235.2,Victoria,NaN,Sub-region 1,Taster 3,@taster3,Winery 11 2011 Vintage Wine,White Blend,Winery 11
52,New Zealand,Wine description for review 52.,Label 7,95,108.8,Hawke's Bay,Region 4,NaN,Taster 4,@taster4,Winery 12 2012 Vintage Wine,Tempranillo-Merlot,Winery 12

**Alternative (less readable):**
```python
top_oceania_wines = reviews[
    ((reviews.country == 'Australia') | (reviews.country == 'New Zealand'))
    & (reviews.points >= 95)
]
```

**Key insight:** Compound conditions combine boolean masks with `&` (AND) and `|` (OR) — each condition must be in parentheses because of Python operator precedence. `.isin([...])` is cleaner than chaining multiple `==` comparisons with `|`.

---
## Session Summary — Day 2 Pandas

| Exercise | Topic | Key Concept |
|----------|-------|-------------|
| 1 | Select a column | `df['col']` or `df.col` — returns a **Series** |
| 2 | First element of Series | `.iloc[0]` — position-based, 0-indexed |
| 3 | First row of DataFrame | `.iloc[0]` on DataFrame → Series (column names become index) |
| 4 | Slice first N values | `.iloc[0:N]` — stop is **exclusive** |
| 5 | Select rows by label list | `.loc[[1,2,3,5,8]]` — list of index labels, non-contiguous |
| 6 | Select rows and columns | `.loc[row_list, col_list]` — both axes by label simultaneously |
| 7 | Range rows + named columns | `loc` stop is **inclusive**; `iloc` stop is **exclusive** |
| 8 | Boolean filter | `df[df.col == value]` — boolean mask selects matching rows |
| 9 | Compound filter | `.isin([...])` for multi-value match; `&`/`\|` to combine masks (parens required) |